[versions]
kotlin = "2.0.20"
jupiterApi = "5.11.2"
jupiterEngine = "5.11.2"
gson = "2.11.0"

[libraries]
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "jupiterApi" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiterEngine" }
gson = { group = "com.google.code.gson", name = "", version.ref = "gson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }